\chapter*{Preface}

\initial{T}his work has been conducted in the context of a joint PhD between Univ. Grenoble Alpes (Grenoble, France) and Ghent University (Ghent, Belgium) and has been funded by Univ. Grenoble Alpes (previously UPMF). The present thesis is presented as a collection of eight chapters, with two introductory chapters, five empirical chapters and a final discussion chapter. The underlying code as well as an online version of this is thesis is available at: https://github.com/lnalborczyk/phd_thesis.

<!--
In Chapter 1, we introduce, review, and discuss the main theoretical frameworks related to rumination and inner speech. In addition to theoretical concepts, we review the methods that have been used to investigate each phenomenon. For inner speech, we also provide a brief and non-exhaustive historical review from 1850 to present days. In Chapter 2, we provide some core technical details related to the methodology we used in our work. This chapter contains elements that could not be included in experimental chapters, such as a brief introduction to surface electromyography and a motivated description of our statistical approach. Because these details usually do not find their place in empirical papers, we wanted to provide the reader this complementary information that, we think, will facilitate the reading of subsequent empirical chapters.

In Chapter 3, we present an experimental protocol aiming to highlight the facial electromyographic correlates of induced rumination. Moreover, we aimed to evaluate whether interfering with the speech motor system (via orofacial relaxation) would disrupt rumination more importantly than a motor interference directed to another part of the body (an arm relaxation). Results of this experiment suggest that induced rumination is accompanied by increased facial muscular activity (as compared to rest) and that an orofacial relaxation would be slightly more efficient in reducing rumination than a non-orofacial relaxation. However, as the increase in facial muscular activity was not restricted to the orofacial area, it is difficult to conclude with absolute certainty that these activations were exclusively related to speech production processes.

In Chapter 4, we present the results of an experiment aiming to differentiate the muscular correlates of different types of rumination. More precisely, we aimed to induce rumination in either a verbal or a non-verbal (e.g., visual) modality to identify modality-specific EMG correlates. Although this inductions in different modalities was not successful, post-hoc comparison of a posteriori groups of verbal versus non-verbal ruminators did not reveal differences in their EMG correlates. These results, although they replicate those presented in Chapter 3 (because the orofacial EMG amplitude was higher after rumination induction than at rest) go against the interpretation of these orofacial muscular correlates being related to speech production processes (because they were not specifically associated to *verbal* rumination). Moreover, we observed opposite effects of relaxation on self-reported state rumination to those we observed in Chapter 3.

In Chapter 5, we examine the muscle-specific electromyographic correlates of inner speech during the production of rounded and spread disyllabic nonwords. We carried out this study to replicate classic findings of the literature and to ensure that our methodology was appropriate to investigate the EMG correlates of inner speech production. Contrary to our predictions, we did not find muscle-specific EMG correlates of inner speech production. We then adopted a classification strategy, and although we were able to attain reasonable accuracy levels in classifying classes of nonwords produces overtly, we were not able to classify classes of nonwords produced covertly. We discuss these findings and their implications for EMG studies of inner speech.

In Chapter 6, we switched to another strategy and instead of examining the peripheral muscular correlates of inner speech production, we aimed to directly interfere with the speech motor system to probe its role in induced rumination. To this end, we used articulatory suppression (here, silent mouthing) following a rumination induction and compared its effects to a control finger-tapping condition. Although the interpretation of the results of this experiment are complicated by certain methodological limitations of the paradigm we used, the results of this experiment suggest that articulatory suppression was not more efficient than finger-tapping in reducing self-reported levels of state rumination. This suggests (in addition to results from previous chapters) that rumination may be a form of inner speech that does not *require* the involvement of the speech motor system.

In Chapter 7, we used the same strategy (articulatory suppression) to examine the role of the speech motor system in rumination. We used a protocol similar to the protocol we used in Chapter 6, except that we used better measures of state rumination, a proper control condition and a more naturalistic form of articulatory suppression (chewing). In addition to rumination, we induced another form of (more adaptive) repetitive thinking: problem-solving. We then compared the effects of articulatory suppression versus finger-tapping on the two thinking styles. Preliminary results suggest that chewing did not disrupt rumination (or problem-solving) more than finger-tapping.

Finally, in Chapter 8, we discuss the overall findings and suggest ways forward from both an experimental and a theoretical perspective.
-->

\newpage
\blankpage
